point_cloud_range: &point_cloud_range [-1.0, -1.0, -1.0, 1.0, 1.0, 1.0]

dataset:
  target: pcld.data.point_cloud_module.PointCloudDataModule_multi_v405
  params:
    dataset_name: "shapenet"
    dataset_folder: "/path/to/data/"
    split_folder: "./configs/data/shapenet_rendering"
    pc_size: 2048
    surface_sampling: true

    batch_size: 4
    num_workers: 4

    only_get_16_category: true

model:
  target: pcld.models.pcl_multi_cond_diffuser_v405.PointCloudLatentDiffuser
  params:
    vae_cfg:
      target: pcld.models.pcl_vae_v1.PointLatentKLModel
      params:
        dim: 768
        num_centers: 1024
        num_freqs: 8
        mask_ratio: 0.15
        encoder_cfg:
          top_k: 32
          hidden_dim: 256
          feat_dim: 0
          depth: 6
          heads: 6
          mlp_dim: 1024
          dim_head: 64
          attn_drop_prob: 0.0
          proj_drop_prob: 0.0
          drop_path_prob: 0.1

        decoder_cfg:
          depth: 8
          heads: 6
          mlp_dim: 1024
          dim_head: 64
          attn_drop_prob: 0.0
          proj_drop_prob: 0.0
          drop_path_prob: 0.1

        loss_cfg:
          target: pcld.modules.losses.klrecdisc.KLChamferDistance
          params:
            kl_weight: 1.0e-5

        scheduler_cfg:
          target: pcld.lr_scheduler.LambdaLinearScheduler
          params:
            warm_up_steps: [ 10000 ]
            cycle_lengths: [ 10000000000000 ]
            f_start: [ 1.e-6 ]
            f_max: [ 1. ]
            f_min: [ 1. ]
        
        ckpt_path: "/path/to/vae.ckpt"
    
    context_cfg:
      target: pcld.modules.conditional_encoders.context_encoder.MultiEncoder
      params:
        modelpath: "/path/to/download/openaiclip-vit-base-patch32/ckpt"
        last_hidden_state: true

    class_encoder_cfg:
      target: pcld.modules.conditional_encoders.class_encoder.ClassEmbedder
      params:
        embed_dim: 768
        n_classes: 13
        key: "class_num"

    denoiser_cfg:
      target: pcld.modules.denoisers.Transformer.myTransformerModel_multi_v405
      params:
        latent_dim: 1024
        ff_size: 4096
        num_layers: 8
        num_heads: 16
        sample_dim: 768
        img_dim: 768
        text_dim: 512
        class_dim: 768
        dropout: 0.0
        dropout_each_cond: 0.5
        dropout_all_cond: 0.1
        retain_all_cond: 0.1

    scheduler_cfg:
      GUIDANCE_SCALE: 1.3
      GUIDANCE_UNCONDP: 0.1
      PREDICT_EPSILON: true
      noise:
        TYPE: "ddpm"
        NUM_TRIAN_STEPS: 1000
        BETA_START: 0.00085
        BETA_END: 0.012
        BETA_SCHEDULE: "scaled_linear"
        VARIANCE_TYPE: "fixed_small"
        CLIP_SAMPLE: true
      denoise:
        TYPE: "ddim"
        NUM_INFERENCE_STEPS: 50
        NUM_TRIAN_STEPS: 1000
        ETA: 0.0
        BETA_START: 0.00085
        BETA_END: 0.012
        BETA_SCHEDULE: "scaled_linear"
        CLIP_SAMPLE: false
        SET_ALPHA_TO_ONE: false
        STEPS_OFFSET: 1

    optim_cfg:
      betas: [0.9, 0.999]
      weight_decay: 1.e-2
      scheduler_cfg:
        target: pcld.lr_scheduler.LambdaLinearScheduler
        params:
          warm_up_steps: [ 10000 ]
          cycle_lengths: [ 10000000000000 ]
          f_start: [ 1.e-6 ]
          f_max: [ 1. ]
          f_min: [ 1. ]

    loss_cfg:
      elbo_weight: 0.0

    context_trainable: false

logger:
  target: pcld.utils.callbacks.MultiCondPointDiffuserLogger
  params:
    step_frequency: 500
    num_samples: 2
    sample_times: 1
    normalize: false
