# -*- coding: utf-8 -*-

import torch
import torch.nn as nn
from einops import rearrange, repeat
from typing import Optional
import math
import warnings


def exists(val):
    return val is not None


def default(val, d):
    return val if exists(val) else d


def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor | nn.Parameter, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    NOTE: this impl is similar to the PyTorch trunc_normal_, the bounds [a, b] are
    applied while sampling the normal with mean/std applied, therefore a, b args
    should be adjusted to match the range of mean, std args.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)


def init_weights(m):
    if isinstance(m, nn.Linear):
        trunc_normal_(m.weight, std=.02)
        if isinstance(m, nn.Linear) and m.bias is not None:
            nn.init.constant_(m.bias, 0)
    elif isinstance(m, nn.LayerNorm):
        nn.init.constant_(m.bias, 0)
        nn.init.constant_(m.weight, 1.0)


class MultiHeadAttention(nn.Module):
    def __init__(self, query_dim, context_dim=None, output_dim=None, heads=8, dim_head=64, causal=False,
                 attn_drop: float = 0.0, proj_drop: float = 0.0):

        super().__init__()
        inner_dim = dim_head * heads
        context_dim = default(context_dim, query_dim)
        self.scale = dim_head ** -0.5
        self.heads = heads
        self.causal = causal

        self.to_q = nn.Linear(query_dim, inner_dim, bias=False)
        self.to_kv = nn.Linear(context_dim, inner_dim * 2, bias=False)
        self.attn_drop = nn.Dropout(attn_drop)

        output_dim = default(output_dim, query_dim)
        self.to_out = nn.Linear(inner_dim, output_dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x, context=None, mask=None):
        h = self.heads

        q = self.to_q(x)
        context = default(context, x)
        k, v = self.to_kv(context).chunk(2, dim=-1)

        q, k, v = map(lambda t: rearrange(t, "b n (h d) -> (b h) n d", h=h), (q, k, v))

        sim = torch.einsum("b i d, b j d -> b i j", q, k) * self.scale

        max_neg_value = -torch.finfo(sim.dtype).max

        if exists(mask):
            mask = rearrange(mask, "b ... -> b (...)")
            mask = repeat(mask, "b j -> (b h) () j", h=h)
            sim.masked_fill_(~mask, max_neg_value)

        if self.causal:
            i, j = sim.shape[-2:]
            causal_mask = torch.ones((i, j), dtype=torch.bool, device=sim.device).triu(j - i + 1)
            sim = sim.masked_fill(causal_mask, max_neg_value)

        # attention, what we cannot get enough of
        attn = sim.softmax(dim=-1)
        attn = self.attn_drop(attn)

        out = torch.einsum("b i j, b j d -> b i d", attn, v)
        out = rearrange(out, "(b h) n d -> b n (h d)", h=h)

        out = self.proj_drop(self.to_out(out))

        return out


class PreNorm(nn.Module):
    def __init__(self, dim: int, fn: nn.Module) -> None:
        super().__init__()
        self.norm = nn.LayerNorm(dim)
        self.fn = fn

    def forward(self, x: torch.FloatTensor, **kwargs) -> torch.FloatTensor:
        return self.fn(self.norm(x), **kwargs) + x


class PostNorm(nn.Module):
    def __init__(self, dim: int, fn: nn.Module) -> None:
        super().__init__()
        self.norm = nn.LayerNorm(dim)
        self.fn = fn

    def forward(self, x: torch.FloatTensor, **kwargs) -> torch.FloatTensor:
        return self.norm(self.fn(x, **kwargs) + x)


def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as "Drop Connect" is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I"ve opted for
    changing the layer and argument names to "drop path" rather than mix DropConnect as a layer name and use
    "survival rate" as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """

    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)

    def extra_repr(self) -> str:
        return "p={}".format(self.drop_prob)


class NormLayer(nn.Module):
    def __init__(self, dim: int, fn: nn.Module, drop_path_prob: float = 0.0, pre_norm: bool = True) -> None:
        super().__init__()

        self.pre_norm = pre_norm
        self.norm = nn.LayerNorm(dim)
        self.drop_path = DropPath(drop_path_prob)
        self.fn = fn

    def forward(self, x: torch.FloatTensor, **kwargs) -> torch.FloatTensor:

        if self.pre_norm:
            return self.drop_path(self.fn(self.norm(x), **kwargs)) + x
        else:
            return self.norm(self.drop_path(self.fn(x, **kwargs)) + x)


class FeedForward(nn.Module):
    def __init__(self, dim: int, hidden_dim: int, ffn_drop: float = 0.0) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, dim)
        )
        self.dropout = nn.Dropout(ffn_drop)

    def forward(self, x: torch.FloatTensor) -> torch.FloatTensor:
        return self.dropout(self.net(x))


class Transformer(nn.Module):
    def __init__(self, dim: int, depth: int, heads: int, dim_head: int, mlp_dim: int, pre_norm: bool = False) -> None:
        super().__init__()

        self.layers = nn.ModuleList([])
        for idx in range(depth):
            layer = nn.ModuleList([NormLayer(dim, MultiHeadAttention(dim, heads=heads, dim_head=dim_head), pre_norm),
                                   NormLayer(dim, FeedForward(dim, mlp_dim), pre_norm)])
            self.layers.append(layer)

        if pre_norm:
            self.final_norm = nn.LayerNorm(dim)
        else:
            self.final_norm = None

    def forward(self, x: torch.FloatTensor) -> torch.FloatTensor:
        for attn, ff in self.layers:
            x = attn(x)
            x = ff(x)

        if self.final_norm:
            x = self.final_norm(x)

        return x


class PerceiverIO(nn.Module):

    def __init__(self,
                 in_channels: int,
                 query_dim: int,
                 latent_dim: int,
                 num_latents: int,
                 cross_heads: int,
                 cross_dim_head: int,
                 cross_mlp_dim: int,
                 latent_heads: int,
                 latent_dim_head: int,
                 latent_mlp_dim: int,
                 depth: int,
                 pre_norm: bool = True):

        super().__init__()

        self.latents = nn.Parameter(torch.randn(num_latents, latent_dim))

        # cross-attention encoder
        self.encoder_block = nn.ModuleList([
            NormLayer(latent_dim, MultiHeadAttention(latent_dim, context_dim=in_channels,
                                                     heads=cross_heads, dim_head=cross_dim_head), pre_norm=pre_norm),
            NormLayer(latent_dim, FeedForward(latent_dim, cross_mlp_dim), pre_norm=pre_norm)
        ])

        # self-attention blocks
        self.self_attn_blocks = nn.ModuleList()
        for i in range(depth):
            self.self_attn_blocks.append(nn.ModuleList([
                NormLayer(
                    latent_dim,
                    MultiHeadAttention(latent_dim, heads=latent_heads, dim_head=latent_dim_head),
                    pre_norm=pre_norm
                ),

                NormLayer(
                    latent_dim,
                    FeedForward(latent_dim, latent_mlp_dim),
                    pre_norm=pre_norm
                )
            ]))

        # cross-attention decoder
        self.decoder_block = nn.ModuleList([
            NormLayer(query_dim, MultiHeadAttention(query_dim, context_dim=latent_dim,
                                                    heads=cross_heads, dim_head=cross_dim_head), pre_norm=pre_norm),
            NormLayer(query_dim, FeedForward(query_dim, cross_mlp_dim), pre_norm=pre_norm)
        ])

    def forward(
            self,
            data,
            queries: Optional[torch.FloatTensor] = None,
            mask: Optional[torch.FloatTensor] = None
    ):
        """

        Args:
            data (torch.FloatTensor):
            queries (torch.FloatTensor):
            mask (torch.FloatTensor):

        Returns:

        """

        b = data.shape[0]

        x = repeat(self.latents, "n d -> b n d", b=b)

        # cross attention only happens once for Perceiver IO
        encoder_cross_attn, encoder_cross_ff = self.encoder_block
        x = encoder_cross_attn(x, context=data, mask=mask)
        x = encoder_cross_ff(x)

        # layers
        for self_attn, self_ff in self.self_attn_blocks:
            x = self_attn(x)
            x = self_ff(x)

        if queries is None:
            return x

        # make sure queries contains batch dimension
        if queries.ndim == 2:
            queries = repeat(queries, "n d -> b n d", b=b)

        # cross attend from decoder queries to latents
        cross_attn_decoder, cross_ff_decoder = self.decoder_block
        latents = cross_attn_decoder(queries, context=x)

        # optional decoder feedforward
        if cross_ff_decoder is not None:
            latents = cross_ff_decoder(latents)

        return latents
